# Generated by Django 4.2.3 on 2023-07-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0002_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='created_at',
        ),
    ]
