# Generated by Django 4.2.3 on 2023-07-18 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0003_remove_email_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
