# Generated by Django 4.2.3 on 2024-02-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0010_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
