# Generated by Django 4.2.3 on 2024-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0013_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='zivotopis.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
