# Generated by Django 4.2.3 on 2024-02-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0014_remove_image_post_remove_post_image_post_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='zivotopis.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='zivotopis.image'),
        ),
    ]
