# Generated by Django 4.2.3 on 2024-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0016_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Predmet:'),
        ),
    ]
