# Generated by Django 4.2.3 on 2024-06-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0017_alter_email_subject'),
    ]

    operations = [
    ]
