# Generated by Django 4.2.3 on 2024-07-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0018_auto_20240613_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(verbose_name='Správa:'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender_email',
            field=models.EmailField(max_length=254, verbose_name='Váš email (povinné):'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender_name',
            field=models.CharField(max_length=100, verbose_name='Vaše meno (povinné):'),
        ),
    ]
