# Generated by Django 4.2.3 on 2024-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0018_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
