# Generated by Django 4.2.3 on 2024-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0019_homepage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name_picture',
            field=models.TextField(blank=True),
        ),
    ]
