# Generated by Django 4.2.3 on 2025-09-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0020_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('bio', 'O mne'), ('trip', 'Výlet'), ('tech', 'IT')], default='bio', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
