# Generated by Django 4.2.11 on 2025-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0021_post_category_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220)),
                ('url', models.URLField(blank=True, null=True)),
                ('now_price', models.IntegerField(blank=True)),
                ('old_price', models.IntegerField(default=0)),
                ('differ_price', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('differ_price', '-created'),
            },
        ),
    ]
