# Generated by Django 4.2.11 on 2025-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivotopis', '0022_ceny'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceny',
            name='source_type',
            field=models.CharField(choices=[('book', 'Kniha'), ('flat', 'Byt')], default='flat', max_length=10),
        ),
        migrations.AlterField(
            model_name='ceny',
            name='now_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
